name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  fonts:
    - family: NotoSansRegular
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
    - family: NotoSansBold
      fonts:
        - asset: assets/fonts/NotoSansKR-Bold.ttf
  uses-material-design: true


